In [2]:
import seaborn as sns
import numpy as np
import pandas as pd
from   scipy import stats
import matplotlib.pyplot as plt
import matplotlib as mpl
import statsmodels.formula.api as sm
import chart_studio.plotly     as py
import os

In [3]:
file_data = 'test.csv'

In [4]:
test_df = pd.read_csv(file_data,sep=',')

In [5]:
test_df.head()

Unnamed: 0     id  Gender      Customer_Type  Age   Type_of_Travel  \
0           0  19556  Female     Loyal Customer   52  Business travel   
1           1  90035  Female     Loyal Customer   36  Business travel   
2           2  12360    Male  disloyal Customer   20  Business travel   
3           3  77959    Male     Loyal Customer   44  Business travel   
4           4  36875  Female     Loyal Customer   49  Business travel   

      Class  Flight_Distance  Inflight_wifi_service  \
0       Eco              160                      5   
1  Business             2863                      1   
2       Eco              192                      2   
3  Business             3377                      0   
4       Eco             1182                      2   

   Departure_Arrival_time_convenient  ...  Inflight_entertainment  \
0                                  4  ...                       5   
1                                  1  ...                       4   
2                                  0  ...                       2   
3                                  0  ...                       1   
4                                  3  ...                       2   

   On-board_service  Leg room_service  Baggage_handling  Checkin_service  \
0                 5                 5                 5                2   
1                 4                 4                 4                3   
2                 4                 1                 3                2   
3                 1                 1                 1                3   
4                 2                 2                 2                4   

   Inflight_service  Cleanliness  Departure_Delay_in_Minutes  \
0                 5            5                          50   
1                 4            5                           0   
2                 2            2                           0   
3                 1            4                           0   
4                 2            4                           0   

   Arrival_Delay_in_Minutes             satisfaction  
0                      44.0                satisfied  
1                       0.0                satisfied  
2                       0.0  neutral or dissatisfied  
3                       6.0                satisfied  
4                      20.0                satisfied  

[5 rows x 25 columns]

In [6]:
import pandas as pd
import sklearn as skl


print(test_df)

       Unnamed: 0     id  Gender      Customer_Type  Age   Type_of_Travel  \
0               0  19556  Female     Loyal Customer   52  Business travel   
1               1  90035  Female     Loyal Customer   36  Business travel   
2               2  12360    Male  disloyal Customer   20  Business travel   
3               3  77959    Male     Loyal Customer   44  Business travel   
4               4  36875  Female     Loyal Customer   49  Business travel   
...           ...    ...     ...                ...  ...              ...   
25971       25971  78463    Male  disloyal Customer   34  Business travel   
25972       25972  71167    Male     Loyal Customer   23  Business travel   
25973       25973  37675  Female     Loyal Customer   17  Personal Travel   
25974       25974  90086    Male     Loyal Customer   14  Business travel   
25975       25975  34799  Female     Loyal Customer   42  Personal Travel   

          Class  Flight_Distance  Inflight_wifi_service  \
0           Eco 

In [7]:
print(test_df.describe())

         Unnamed: 0             id           Age  Flight_Distance  \
count  25976.000000   25976.000000  25976.000000     25976.000000   
mean   12987.500000   65005.657992     39.620958      1193.788459   
std     7498.769632   37611.526647     15.135685       998.683999   
min        0.000000      17.000000      7.000000        31.000000   
25%     6493.750000   32170.500000     27.000000       414.000000   
50%    12987.500000   65319.500000     40.000000       849.000000   
75%    19481.250000   97584.250000     51.000000      1744.000000   
max    25975.000000  129877.000000     85.000000      4983.000000   

       Inflight_wifi_service  Departure_Arrival_time_convenient  \
count           25976.000000                       25976.000000   
mean                2.724746                           3.046812   
std                 1.335384                           1.533371   
min                 0.000000                           0.000000   
25%                 2.000000               

In [8]:
dataset = test_df.drop("id", axis=1)
label = test_df["id"].copy()

In [9]:
dataset.isnull()

Unnamed: 0  Gender  Customer_Type    Age  Type_of_Travel  Class  \
0           False   False          False  False           False  False   
1           False   False          False  False           False  False   
2           False   False          False  False           False  False   
3           False   False          False  False           False  False   
4           False   False          False  False           False  False   
...           ...     ...            ...    ...             ...    ...   
25971       False   False          False  False           False  False   
25972       False   False          False  False           False  False   
25973       False   False          False  False           False  False   
25974       False   False          False  False           False  False   
25975       False   False          False  False           False  False   

       Flight_Distance  Inflight_wifi_service  \
0                False                  False   
1                False                  False   
2                False                  False   
3                False                  False   
4                False                  False   
...                ...                    ...   
25971            False                  False   
25972            False                  False   
25973            False                  False   
25974            False                  False   
25975            False                  False   

       Departure_Arrival_time_convenient  Ease_of_Online_booking  ...  \
0                                  False                   False  ...   
1                                  False                   False  ...   
2                                  False                   False  ...   
3                                  False                   False  ...   
4                                  False                   False  ...   
...                                  ...                     ...  ...   
25971                              False                   False  ...   
25972                              False                   False  ...   
25973                              False                   False  ...   
25974                              False                   False  ...   
25975                              False                   False  ...   

       Inflight_entertainment  On-board_service  Leg room_service  \
0                       False             False             False   
1                       False             False             False   
2                       False             False             False   
3                       False             False             False   
4                       False             False             False   
...                       ...               ...               ...   
25971                   False             False             False   
25972                   False             False             False   
25973                   False             False             False   
25974                   False             False             False   
25975                   False             False             False   

       Baggage_handling  Checkin_service  Inflight_service  Cleanliness  \
0                 False            False             False        False   
1                 False            False             False        False   
2                 False            False             False        False   
3                 False            False             False        False   
4                 False            False             False        False   
...                 ...              ...               ...          ...   
25971             False            False             False        False   
25972             False            False             False        False   
25973             False            False             False        False   
25974             False            False             False        False  

In [10]:
dataset.isnull().sum()

Unnamed: 0                            0
Gender                                0
Customer_Type                         0
Age                                   0
Type_of_Travel                        0
Class                                 0
Flight_Distance                       0
Inflight_wifi_service                 0
Departure_Arrival_time_convenient     0
Ease_of_Online_booking                0
Gate_location                         0
Food_and_drink                        0
Online_boarding                       0
Seat_comfort                          0
Inflight_entertainment                0
On-board_service                      0
Leg room_service                      0
Baggage_handling                      0
Checkin_service                       0
Inflight_service                      0
Cleanliness                           0
Departure_Delay_in_Minutes            0
Arrival_Delay_in_Minutes             83
satisfaction                          0
dtype: int64

In [11]:
dataset.isnull().any(axis=1)

0        False
1        False
2        False
3        False
4        False
         ...  
25971    False
25972    False
25973    False
25974    False
25975    False
Length: 25976, dtype: bool

In [12]:
dataset = test_df.drop("Arrival_Delay_in_Minutes", axis=1)

In [13]:
Gender_cat = test_df[['Gender']]
Type_of_Travel_cat = test_df[['Type_of_Travel']]
Class_cat = test_df[['Class']]
Customer_Type_cat = test_df[['Customer_Type']]
satisfaction_cat = test_df[['satisfaction']]
print(Gender_cat.head(10))
print(Type_of_Travel_cat.head(10))
print(Class_cat.head(10))
print(Customer_Type_cat.head(10))
print(satisfaction_cat.head(10))

   Gender
0  Female
1  Female
2    Male
3    Male
4  Female
5    Male
6  Female
7  Female
8    Male
9  Female
    Type_of_Travel
0  Business travel
1  Business travel
2  Business travel
3  Business travel
4  Business travel
5  Business travel
6  Business travel
7  Business travel
8  Business travel
9  Business travel
      Class
0       Eco
1  Business
2       Eco
3  Business
4       Eco
5       Eco
6  Business
7  Business
8       Eco
9  Business
       Customer_Type
0     Loyal Customer
1     Loyal Customer
2  disloyal Customer
3     Loyal Customer
4     Loyal Customer
5     Loyal Customer
6     Loyal Customer
7     Loyal Customer
8     Loyal Customer
9     Loyal Customer
              satisfaction
0                satisfied
1                satisfied
2  neutral or dissatisfied
3                satisfied
4                satisfied
5                satisfied
6                satisfied
7                satisfied
8                satisfied
9                satisfied


In [14]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
Gender_cat_encoded = ordinal_encoder.fit_transform(Gender_cat)
print(Gender_cat_encoded[:10])

Type_of_Travel_cat_encoded = ordinal_encoder.fit_transform(Type_of_Travel_cat)
print(Type_of_Travel_cat_encoded[:10])

Class_cat_encoded = ordinal_encoder.fit_transform(Class_cat)
print(Class_cat_encoded[:10])

Customer_Type_cat_encoded = ordinal_encoder.fit_transform(Customer_Type_cat)
print(Customer_Type_cat_encoded[:10])

satisfaction_cat_encoded = ordinal_encoder.fit_transform(satisfaction_cat)
print(satisfaction_cat_encoded[:10])

[[0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]]
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [15]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
Gender_cat_one_hot = one_hot_encoder.fit_transform(Gender_cat)
print(Gender_cat_one_hot.toarray().shape)
print(Gender_cat_one_hot.toarray())

from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
Type_of_Travel_cat_one_hot = one_hot_encoder.fit_transform(Type_of_Travel_cat)
print(Type_of_Travel_cat_one_hot.toarray().shape)
print(Type_of_Travel_cat_one_hot.toarray())

from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
Class_cat_one_hot = one_hot_encoder.fit_transform(Class_cat)
print(Class_cat_one_hot.toarray().shape)
print(Class_cat_one_hot.toarray())

from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
Customer_Type_cat_one_hot = one_hot_encoder.fit_transform(Customer_Type_cat)
print(Customer_Type_cat_one_hot.toarray().shape)
print(Customer_Type_cat_one_hot.toarray())

from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
satisfaction_cat_one_hot = one_hot_encoder.fit_transform(satisfaction_cat)
print(satisfaction_cat_one_hot.toarray().shape)
print(satisfaction_cat_one_hot.toarray())

(25976, 2)
[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]
(25976, 2)
[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]
(25976, 3)
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
(25976, 2)
[[1. 0.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
(25976, 2)
[[0. 1.]
 [0. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]


In [16]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
l_values = dataset[['Flight_Distance']]
scaled_values = min_max_scaler.fit(l_values)
print(min_max_scaler.transform(l_values)[0:10])

[[0.02605008]
 [0.57189015]
 [0.03251212]
 [0.67568659]
 [0.23243134]
 [0.05654281]
 [0.79886914]
 [0.50989499]
 [0.10601777]
 [0.34592084]]


In [17]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
l_values = dataset[['Flight_Distance']]
scaled_values = standard_scaler.fit(l_values)
print(standard_scaler.transform(l_values)[0:10])

[[-1.03517064]
 [ 1.67144329]
 [-1.00312786]
 [ 2.18613052]
 [-0.01180422]
 [-0.88396876]
 [ 2.79694609]
 [ 1.36403283]
 [-0.63864119]
 [ 0.55094718]]


In [18]:
from sklearn.compose import ColumnTransformer
num_attrs = ["Inflight_wifi_service", "Flight_Distance", "Age", "Departure_Arrival_time_convenient", "Seat_comfort","Inflight_entertainment", "On-board_service", "Leg room_service"
             ,"Baggage_handling", "Checkin_service", "Cleanliness", "Departure_Delay_in_Minutes"]
text_attrs = ["Gender", "Class","Customer_Type","Type_of_Travel"]

pipeline = ColumnTransformer([
                              ("numeric", StandardScaler(), num_attrs),
                              ("text", OneHotEncoder(), text_attrs)
])
preprocessed_dataset = pipeline.fit_transform(dataset)

In [19]:
from sklearn.model_selection import train_test_split
# Realizamos la partición de nuestro dataset en un conjunto de entrenamiento y otro de test (20%)
X_train, X_test, y_train, y_test = train_test_split(preprocessed_dataset, label, test_size=0.2, random_state=42)

In [1]:
from sklearn.svm import SVC

# Creamos el clasificador SVM lineal
classifier =  SVC()

# Realizamos el entrenamiento
classifier.fit(X_train, y_train)

# Obtenemos el accuracy de nuestro modelo para el conjunto de test
print(classifier.score(X_test, y_test))

NameError: name 'X_train' is not defined